import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  authenticated,
  unauthenticated,
}: Readonly<{
  children: ReactNode;
  authenticated: ReactNode;
  unauthenticated: ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {children}
          {session ? authenticated : unauthenticated}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
